In [3]:
import pandas as pd
from time import *
plastic_data=pd.read_csv("knapsack1.csv")

In [15]:
plastic_data

     item  profit  weight         product product_type
0       1     585     485      Laptop Bag        cloth
1       2     194      94       Briefcase      plastic
2       3     426     326  Trashy shopper      plastic
3       4     606     506          Wallet        cloth
4       5     348     248          Sticks         wood
..    ...     ...     ...             ...          ...
495   496     263     163         Textile        cloth
496   497     406     306           Steel        steel
497   498     601     501            Wood         wood
498   499     134      34            Lead        steel
499   500     577     477      Fertilizer      plastic

[500 rows x 5 columns]

In [16]:
#0-1 Knapsack
wt=(plastic_data['weight']).to_numpy()
wt

array([485,  94, 326, 506, 248, 416, 421, 992, 322, 649, 795, 237,  43,
       457, 845, 815, 955, 446, 252, 422,   9, 791, 901, 359, 122, 667,
        94, 598, 738,   7, 574, 544, 715, 334, 882, 766, 367, 994, 984,
       893, 299, 633, 433, 131, 682, 428,  72, 700, 874, 617, 138, 874,
       856, 720, 145, 419, 995, 794, 529, 196, 199, 997, 277, 116,  97,
       908, 719, 539, 242, 707, 107, 569, 122, 537,  70, 931,  98, 726,
       600, 487, 645, 772, 267, 513, 972,  81, 895, 943, 213,  58, 748,
       303, 487, 764, 923, 536,  29, 724, 674, 789, 540, 479, 554, 142,
       467, 339,  46, 641, 710, 196, 553, 494, 191,  66, 724, 824, 730,
       208, 988, 711,  90, 800, 340, 314, 549, 289, 196, 401, 865, 466,
       678, 689, 570, 833, 936, 225, 722, 244, 651, 849, 123, 113, 431,
       379, 508, 361, 585,  65, 853, 486, 642, 686, 992, 286, 725, 889,
       286,  24, 812, 491, 859, 891, 663,  90,  88, 181, 179, 214, 187,
        17, 619, 472, 261, 418, 846, 419, 192, 356, 261, 682, 514, 306,
       886, 201, 530, 385, 849, 952, 294, 500, 799, 194, 391, 737, 330,
       324, 298, 992, 790, 224, 275, 260, 826,  97,  72, 210, 866, 649,
       951, 919, 748,  63, 685, 958, 956, 804, 564, 518, 183, 428, 400,
       537, 721, 346, 207, 153, 323, 971, 611, 662, 116, 197, 109,  91,
       795, 529, 343, 126, 862, 747, 685, 469,  10, 770, 881, 934, 984,
       723, 403, 895, 360, 568, 449, 172, 541, 958, 272, 383, 877, 308,
       359, 970, 707, 583, 308,  48, 770, 930,  30, 569, 208,   3, 311,
        20, 100, 609, 939, 887, 422, 825, 785, 930, 370, 904, 989, 241,
       969, 379, 143, 376, 972, 962,  28, 889,  61, 443, 638, 216, 348,
       338, 347, 160,  66, 406, 391, 159, 638,  31, 295, 204, 826, 420,
       196, 153, 449, 425, 855, 331, 143, 565, 487, 838, 140,   9, 564,
       918, 615, 533, 135, 232, 564, 957, 360, 591, 793, 576, 163, 746,
       859, 377, 760, 858, 711,  86, 662, 434, 159, 558, 660, 279, 268,
       840, 948, 735, 315, 574, 676, 126, 341, 912, 689, 739, 894, 821,
       706, 625, 490, 917, 478, 201, 671, 993, 932, 149, 899,  52, 237,
       759, 187, 267, 472, 256, 772, 783,  98, 117, 906, 516, 911, 180,
       635,  25, 225, 380, 823, 712, 164, 266, 343, 216, 732, 448, 502,
       541, 740, 664, 576, 954, 612, 726, 902, 772, 454, 531, 411, 943,
       973, 750, 703, 327, 850, 917,  77,   5, 220, 113, 802, 913, 403,
       791, 181, 998,  10, 859, 525, 345, 919, 431, 668, 675, 527, 833,
       462, 438, 291, 523, 605, 916, 457, 420, 405, 115, 417, 660, 279,
       261, 685, 772, 596, 388, 307, 764, 224, 843, 322, 206, 840, 407,
       975, 639, 401, 852,  91, 542, 327,  60, 330, 757, 182,  82, 603,
       637, 793,  93, 615, 614, 733, 136, 864, 187,  16, 102, 863, 972,
       987, 163, 306, 501,  34, 477], dtype=int64)

In [17]:
pf=(plastic_data['profit']).to_numpy()
pf

array([ 585,  194,  426,  606,  348,  516,  521, 1092,  422,  749,  895,
        337,  143,  557,  945,  915, 1055,  546,  352,  522,  109,  891,
       1001,  459,  222,  767,  194,  698,  838,  107,  674,  644,  815,
        434,  982,  866,  467, 1094, 1084,  993,  399,  733,  533,  231,
        782,  528,  172,  800,  974,  717,  238,  974,  956,  820,  245,
        519, 1095,  894,  629,  296,  299, 1097,  377,  216,  197, 1008,
        819,  639,  342,  807,  207,  669,  222,  637,  170, 1031,  198,
        826,  700,  587,  745,  872,  367,  613, 1072,  181,  995, 1043,
        313,  158,  848,  403,  587,  864, 1023,  636,  129,  824,  774,
        889,  640,  579,  654,  242,  567,  439,  146,  741,  810,  296,
        653,  594,  291,  166,  824,  924,  830,  308, 1088,  811,  190,
        900,  440,  414,  649,  389,  296,  501,  965,  566,  778,  789,
        670,  933, 1036,  325,  822,  344,  751,  949,  223,  213,  531,
        479,  608,  461,  685,  165,  953,  586,  742,  786, 1092,  386,
        825,  989,  386,  124,  912,  591,  959,  991,  763,  190,  188,
        281,  279,  314,  287,  117,  719,  572,  361,  518,  946,  519,
        292,  456,  361,  782,  614,  406,  986,  301,  630,  485,  949,
       1052,  394,  600,  899,  294,  491,  837,  430,  424,  398, 1092,
        890,  324,  375,  360,  926,  197,  172,  310,  966,  749, 1051,
       1019,  848,  163,  785, 1058, 1056,  904,  664,  618,  283,  528,
        500,  637,  821,  446,  307,  253,  423, 1071,  711,  762,  216,
        297,  209,  191,  895,  629,  443,  226,  962,  847,  785,  569,
        110,  870,  981, 1034, 1084,  823,  503,  995,  460,  668,  549,
        272,  641, 1058,  372,  483,  977,  408,  459, 1070,  807,  683,
        408,  148,  870, 1030,  130,  669,  308,  103,  411,  120,  200,
        709, 1039,  987,  522,  925,  885, 1030,  470, 1004, 1089,  341,
       1069,  479,  243,  476, 1072, 1062,  128,  989,  161,  543,  738,
        316,  448,  438,  447,  260,  166,  506,  491,  259,  738,  131,
        395,  304,  926,  520,  296,  253,  549,  525,  955,  431,  243,
        665,  587,  938,  240,  109,  664, 1018,  715,  633,  235,  332,
        664, 1057,  460,  691,  893,  676,  263,  846,  959,  477,  860,
        958,  811,  186,  762,  534,  259,  658,  760,  379,  368,  940,
       1048,  835,  415,  674,  776,  226,  441, 1012,  789,  839,  994,
        921,  806,  725,  590, 1017,  578,  301,  771, 1093, 1032,  249,
        999,  152,  337,  859,  287,  367,  572,  356,  872,  883,  198,
        217, 1006,  616, 1011,  280,  735,  125,  325,  480,  923,  812,
        264,  366,  443,  316,  832,  548,  602,  641,  840,  764,  676,
       1054,  712,  826, 1002,  872,  554,  631,  511, 1043, 1073,  850,
        803,  427,  950, 1017,  177,  105,  320,  213,  902, 1013,  503,
        891,  281, 1098,  110,  959,  625,  445, 1019,  531,  768,  775,
        627,  933,  562,  538,  391,  623,  705, 1016,  557,  520,  505,
        215,  517,  760,  379,  361,  785,  872,  696,  488,  407,  864,
        324,  943,  422,  306,  940,  507, 1075,  739,  501,  952,  191,
        642,  427,  160,  430,  857,  282,  182,  703,  737,  893,  193,
        715,  714,  833,  236,  964,  287,  116,  202,  963, 1072, 1087,
        263,  406,  601,  134,  577], dtype=int64)

In [46]:
#Setting knapsack capacity to 500
n=len(wt)
W=500
start = time()
F = [[0 for i in range(0,n)] for j in range(0,W)] 
for i in range(1,n):
    for j in range(1,W):
            if (j-wt[i])<0:
                F[i][j]=F[i-1][j]
            elif (j-wt[i])>=0:
                F[i][j]=max(F[i-1][j],pf[i]+F[i-1][j-wt[i]])

stop = time()
print("Execution time of 0-1 knapsack is {} seconds.".format(stop-start))
print('Maximum Profit is:',F[n-1][W-1])

Execution time of 0-1 knapsack is 0.6362955570220947 seconds.
Maximum Profit is: 2596

In [1]:
#Fractional Knapsack
import warnings
warnings.filterwarnings('ignore')

In [4]:
data=pd.read_csv("knapsack1.csv")
data['Ratio']=data['profit']/data['weight']
data

     item  profit  weight         product product_type     Ratio
0       1     585     485      Laptop Bag        cloth  1.206186
1       2     194      94       Briefcase      plastic  2.063830
2       3     426     326  Trashy shopper      plastic  1.306748
3       4     606     506          Wallet        cloth  1.197628
4       5     348     248          Sticks         wood  1.403226
..    ...     ...     ...             ...          ...       ...
495   496     263     163         Textile        cloth  1.613497
496   497     406     306           Steel        steel  1.326797
497   498     601     501            Wood         wood  1.199601
498   499     134      34            Lead        steel  3.941176
499   500     577     477      Fertilizer      plastic  1.209644

[500 rows x 6 columns]

In [5]:
data=data.sort_values('Ratio',ascending=False)
data

     item  profit  weight          product product_type      Ratio
271   272     103       3           Tables         wood  34.333333
423   424     105       5          Campers         wood  21.000000
29     30     107       7       Herbicides         wood  15.285714
20     21     109       9  Concrete Wastes         wood  12.111111
323   324     109       9       Vegetables      plastic  12.111111
..    ...     ...     ...              ...          ...        ...
371   372    1093     993         Pump oil        steel   1.100705
37     38    1094     994        Gunpowder         wood   1.100604
56     57    1095     995            Drums         wood   1.100503
61     62    1097     997       Yard Waste      plastic   1.100301
431   432    1098     998      Grease trap      plastic   1.100200

[500 rows x 6 columns]

In [6]:
data['Solution set']=[0 for i in range(0,len(data))]
data

,item,profit,weight,product,product_type,Ratio,Solution set
271,272,103,3,Tables,wood,34.333333,0
423,424,105,5,Campers,wood,21.000000,0
29,30,107,7,Herbicides,wood,15.285714,0
20,21,109,9,Concrete Wastes,wood,12.111111,0
323,324,109,9,Vegetables,plastic,12.111111,0
...,...,...,...,...,...,...,...
371,372,1093,993,Pump oil,steel,1.100705,0
37,38,1094,994,Gunpowder,wood,1.100604,0
56,57,1095,995,Drums,wood,1.100503,0
61,62,1097,997,Yard Waste,plastic,1.100301,0
431,432,1098,998,Grease trap,plastic,1.100200,0

In [7]:
#Setting capacity of knapsack to 500
W=500
total=profit=0
for i in range(0,len(data)):
    if (total+data['weight'].iloc[i] <= W):
        data['Solution set'].iloc[i]=1
        total=total+data['weight'].iloc[i]
    else:
        data['Solution set'].iloc[i]=(W-total)/data['weight'].iloc[i]
        total = W
        break
print(data)

     item  profit  weight          product product_type      Ratio  \
271   272     103       3           Tables         wood  34.333333
423   424     105       5          Campers         wood  21.000000
29     30     107       7       Herbicides         wood  15.285714
20     21     109       9  Concrete Wastes         wood  12.111111
323   324     109       9       Vegetables      plastic  12.111111
..    ...     ...     ...              ...          ...        ...
371   372    1093     993         Pump oil        steel   1.100705
37     38    1094     994        Gunpowder         wood   1.100604
56     57    1095     995            Drums         wood   1.100503
61     62    1097     997       Yard Waste      plastic   1.100301
431   432    1098     998      Grease trap      plastic   1.100200

     Solution set
271           1.0
423           1.0
29            1.0
20            1.0
323           1.0
..            ...
371           0.0
37            0.0
56            0.0
61            0.0
431           0.0

[500 rows x 7 columns]

In [8]:
data.head(50)

,item,profit,weight,product,product_type,Ratio,Solution set
271,272,103,3,Tables,wood,34.333333,1.000000
423,424,105,5,Campers,wood,21.000000,1.000000
29,30,107,7,Herbicides,wood,15.285714,1.000000
20,21,109,9,Concrete Wastes,wood,12.111111,1.000000
323,324,109,9,Vegetables,plastic,12.111111,1.000000
432,433,110,10,Gasoline,glass,11.000000,1.000000
242,243,110,10,Water based paint,plastic,11.000000,1.000000
490,491,116,16,Mercury,glass,7.250000,1.000000
169,170,117,17,Lab Equipments,glass,6.882353,1.000000
273,274,120,20,Staples,wood,6.000000,1.000000
157,158,124,24,Dustbins,plastic,5.166667,1.000000
391,392,125,25,Digestate,steel,5.000000,1.000000
292,293,128,28,Syringes,wood,4.571429,1.000000
96,97,129,29,Boombox,plastic,4.448276,1.000000
268,269,130,30,Ovens,steel,4.333333,1.000000
307,308,131,31,Erasers,plastic,4.225806,1.000000
498,499,134,34,Lead,steel,3.941176,1.000000
12,13,143,43,Cups,glass,3.325581,1.000000
106,107,146,46,Circuit Board,wood,3.173913,1.000000
265,266,148,48,Needles,steel,3.083333,1.000000
375,376,152,52,Nicad batteries,plastic,2.923077,1.000000
89,90,158,58,Sludges,plastic,2.724138,0.068966
475,476,160,60,Tires,plastic,2.666667,0.000000
294,295,161,61,Light fixtures,plastic,2.639344,0.000000
211,212,163,63,Obaapa,steel,2.587302,0.000000
147,148,165,65,Copiers,wood,2.538462,0.000000
113,114,166,66,Servers,wood,2.515152,0.000000
302,303,166,66,Branches,wood,2.515152,0.000000
74,75,170,70,Lawn movers,steel,2.428571,0.000000
46,47,172,72,Swarf,steel,2.388889,0.000000
204,205,172,72,Drugs,plastic,2.388889,0.000000
422,423,177,77,Shrubs,wood,2.298701,0.000000
85,86,181,81,Stones,plastic,2.234568,0.000000
479,480,182,82,Plaster,plastic,2.219512,0.000000
343,344,186,86,Brush,plastic,2.162791,0.000000
164,165,188,88,Milk Packets,plastic,2.136364,0.000000
163,164,190,90,Timber Waste,wood,2.111111,0.000000
120,121,190,90,Modem,wood,2.111111,0.000000
233,234,191,91,Cockroach sprays,plastic,2.098901,0.000000
472,473,191,91,Paint,plastic,2.098901,0.000000
483,484,193,93,Pulp,wood,2.075269,0.000000
1,2,194,94,Briefcase,plastic,2.063830,0.000000
26,27,194,94,Bricks,wood,2.063830,0.000000
64,65,197,97,Gas Cylinders,steel,2.030928,0.000000
203,204,197,97,Dyes,plastic,2.030928,0.000000
76,77,198,98,Motor Cycles,steel,2.020408,0.000000
384,385,198,98,Grease,steel,2.020408,0.000000
274,275,200,100,Grass,plastic,2.000000,0.000000
491,492,202,102,Plastic,plastic,1.980392,0.000000
70,71,207,107,Inks,plastic,1.934579,0.000000

In [9]:
bag=data[data['Solution set']==1.00]
print(bag)

     item  profit  weight            product product_type      Ratio  \
271   272     103       3             Tables         wood  34.333333
423   424     105       5            Campers         wood  21.000000
29     30     107       7         Herbicides         wood  15.285714
20     21     109       9    Concrete Wastes         wood  12.111111
323   324     109       9         Vegetables      plastic  12.111111
432   433     110      10           Gasoline        glass  11.000000
242   243     110      10  Water based paint      plastic  11.000000
490   491     116      16            Mercury        glass   7.250000
169   170     117      17     Lab Equipments        glass   6.882353
273   274     120      20            Staples         wood   6.000000
157   158     124      24           Dustbins      plastic   5.166667
391   392     125      25          Digestate        steel   5.000000
292   293     128      28           Syringes         wood   4.571429
96     97     129      29            Boombox      plastic   4.448276
268   269     130      30              Ovens        steel   4.333333
307   308     131      31            Erasers      plastic   4.225806
498   499     134      34               Lead        steel   3.941176
12     13     143      43               Cups        glass   3.325581
106   107     146      46      Circuit Board         wood   3.173913
265   266     148      48            Needles        steel   3.083333
375   376     152      52    Nicad batteries      plastic   2.923077

     Solution set
271           1.0
423           1.0
29            1.0
20            1.0
323           1.0
432           1.0
242           1.0
490           1.0
169           1.0
273           1.0
157           1.0
391           1.0
292           1.0
96            1.0
268           1.0
307           1.0
498           1.0
12            1.0
106           1.0
265           1.0
375           1.0

In [10]:
bag['product_type']

271       wood
423       wood
29        wood
20        wood
323    plastic
432      glass
242    plastic
490      glass
169      glass
273       wood
157    plastic
391      steel
292       wood
96     plastic
268      steel
307    plastic
498      steel
12       glass
106       wood
265      steel
375    plastic
Name: product_type, dtype: object

In [11]:
import seaborn as sns
sns.countplot(y='product_type',data=bag,order = data['product_type'].value_counts().sort_values().index)

ModuleNotFoundError: No module named 'seaborn'

In [12]:
start = time()
for i in range(0,len(data)):
    profit=profit+data['profit'].iloc[i]*data['Solution set'].iloc[i]
stop = time()
print("Execution time of fractional knapsack is {} seconds.".format(stop-start))
print('Maximum Profit is :',profit)

Execution time of fractional knapsack is 0.022007226943969727 seconds.
Maximum Profit is : 2606.896551724138

In [45]:
W=500
total=profit=0
start = time()
for i in range(0,len(data)):
    if (total+data['weight'].iloc[i] <= W):
        data['Solution set'].iloc[i]=1
        total=total+data['weight'].iloc[i]
    else:
        data['Solution set'].iloc[i]=(W-total)/data['weight'].iloc[i]
        total = W
        break
for i in range(0,len(data)):
    profit=profit+data['profit'].iloc[i]*data['Solution set'].iloc[i]
stop = time()
print("Execution time of fractional knapsack is {} seconds.".format(stop-start))

Execution time of fractional knapsack is 0.025935649871826172 seconds.